# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-nodejs

name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  ci:
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4

    # https://oxc.rs/docs/guide/usage/linter.html#github-actions
    - run: npx --yes oxlint@0.15 --format=github --deny-warnings
